- hosts: 165.227.72.93
  tasks:
  - name: Install all packages
    apt:
     name: 
      - apache2
      - git
      - tree
     state: latest 

  - name: Start apache2
    service:
      name: apache2
      state: started
      enabled: yes   

  - name: Create group kaizen
    group:
      name: kaizen
      state: present

  - name: Create group devops
    group:
      name: devops
      state: present

  - name: Create group qa
    group:
      name: qa
      state: present 

  - name: Add user aijan and add to kaizen group
    user:
      name: aijan
      group: kaizen
      append: yes       

  - name: Add user tester and add to qa group
    user:
      name: tester
      group: qa
      append: yes       

  - name: Copy files from Homework1
    copy:
      src: "./"
      dest: /root/  