- name: Download wordpress
  get_url: 
    url: "{{ url }}"
    dest: "{{ tar_file }}"

- name: Extract file
  unarchive:
    src: "{{ tar_file }}"
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes

# - name: Template a file to html                                  #this part is giving me error
#   template:                    
#     src: roles/wordpress/templates/wp-config-sample.php.j2
#     dest: /var/www/html/wp-config.php

# handlers:   
- name: Restart Apache
  service:
    name: "{{ package }}"
    state: restarted